<?php

namespace balou\TemplateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlocHtmlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocHtmlRepository extends EntityRepository
{
}
