<?php

namespace balou\PageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * pageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pageRepository extends EntityRepository
{
	function findPage(){
		return $this->getEntityManager()->createQueryBuilder()
			->add('select', 'p')
			->add('from', 'page pa')
			->add('where', 'p.is_published = :published')
			->setParameter('published', true)
			->getResult();
	}
}
