<?php

namespace balou\MenuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * blocmenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class blocmenuRepository extends EntityRepository
{
}
