balou_home_homepage:
    path:     /
    defaults: { _controller: balouHomeBundle:Default:index}

admin_notes:
    path:     /admin/notes
    defaults: { _controller: balouHomeBundle:Notes:index}

admin_notes_show:
    path:     /admin/notes
    defaults: { _controller: balouHomeBundle:Notes:show}

admin_notes_edit:
    path:     /admin/notes
    defaults: { _controller: balouHomeBundle:Notes:edit}

admin_notes_delete:
    path:     /admin/notes
    defaults: { _controller: balouHomeBundle:Notes:delete}

admin_notes_new:
    path:     /admin/notes
    defaults: { _controller: balouHomeBundle:Notes:new}