<?php

namespace balou\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotesRepository extends EntityRepository
{
	function findNote(){
		return $this->getEntityManager()->createQueryBuilder('n')
			->select('n')
			->from('balouHomeBundle:Notes','n')
			->orderBy('n.createdAt', 'DESC')
			->getQuery()
    		->setMaxResults(1)
			->getSingleResult();
	}
}
